name: Sync Github Repos To Gitee

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Gitee 
      uses: Yikun/hub-mirror-action@v1.2 #使用Yikun开发的hub-mirror-action
      with:
        src: github/TJKkking #源端账户名
        dst: gitee/JACKYTOO #目的端账户名
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} #SSH密钥对中的私钥，即 id_rsa
        dst_token:  ${{ secrets.GITEE_TOKEN }} #Gitee账户的私人令牌
        account_type: user #账户类型
        clone_style: "ssh" #使用ssh方式进行clone，也可以使用https
        debug: true #启用后会显示所有执行命令
